services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/seith/postgresql/:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=airbnbCloneDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
